# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6279d55fa60453ef2b1deed0173734eb07421c361baf88dab59c54e8d643f786ddc53b443d96eac5e3c193f071ff3b17c5b0f2b09f9c49ac9c9cce23c43067e4

test:
  secret_key_base: f58b365ee2a3546c2faf8e6fd062699ae32a964242408378b02320346afd4da357bdbeaca02e9b09851cbb57ae142d1606bfb836930a1a0a1ea683e214015ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
