# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e209e82603f0a412c4db0d2ba66ef01e9f05051039438b0c9e5f2e0c3dbfbab286d5c30a4a1ed7ee7c34be246edfb2787a43b83067eb07ad209f20d36f6aea0

test:
  secret_key_base: 94b47106ed63f930fa0af88b2d1da0ecbe8c2398608243c637d211e0db882b5b5124919fc404b5c8dd705a5a498627595cad92776bcf929d8e8ad79f56f531ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
