name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

concurrency:
  group: production_deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 20250622

      - name: Precompile assets
        run: |
          bundle exec rails assets:precompile

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Create version tag
        run: |
          git add public/assets
          git commit -m "Add precompiled assets [skip ci]"
          VERSION=$(date +%Y%m%d%H%M%S)
          git tag v$VERSION
          git push origin v$VERSION
          git push origin main
          echo "VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 170.64.201.79 >> ~/.ssh/known_hosts

      - name: Deploy to production
        run: |
          BRANCH=${{ env.VERSION }} bundle exec cap production deploy
